name: '🚀 ci'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_and_test:
    name: 🚀 build  and test
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v4
      - name: 🟢 node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: 📦 install
        run: npm ci
      - name: 🏗️ build
        run: npm run build
      - name: 🔍 lint
        run: npm run lint
      - name: 🧪 test
        run: npm test
      - name: 📤 upload junit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: junit.xml
      - name: 📤 upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
